version: "1.29.2"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/usr/backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: Password
      MYSQL_DB: todolist_vol

  mysql:
    image: mysql:latest
    volumes:
      - todolist_vol:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: todolist_vol

volumes:
  todolist_vol:

#  app:
#    image: openjdk:17-jdk-alpine
#    command: docker build --build-arg JAR_FILE=build/libs/\*.jar -t springio/ToDoList-docker .
#    ports:
#      - <source>:<des>
#    working_dir: /ToDoList
#    volumes:
#      - ./:/ToDoList
#    environment:
#      MYSQL_HOST: mysql
#      MYSQL_USER: root
#      MYSQL_PASSWORD: Password
#      MYSQL_DB: todolist_vol